"""
HermesWork catalog -- static AGENTS and MCP_TOOLS data.
Extracted from app.py to keep that module small enough to edit safely.
"""

AGENTS = [
    {"id": 1, "name": "CAMELDebateAgent", "paper": "Li et al., NeurIPS 2023", "capability": "Multi-agent role-play debate", "status": "active"},
    {"id": 2, "name": "ReActAgent", "paper": "Yao et al., ICLR 2023", "capability": "Reason-Act-Observe loops", "status": "active"},
    {"id": 3, "name": "ChainOfThoughtAgent", "paper": "Wei et al., NeurIPS 2022", "capability": "Step-by-step scoring", "status": "active"},
    {"id": 4, "name": "MultiAgentOrchestrator", "paper": "Park et al., UIST 2023", "capability": "Generative agents orchestration", "status": "active"},
    {"id": 5, "name": "AnomalyScannerAgent", "paper": "Statistical Process Control", "capability": "Proactive anomaly detection", "status": "active"},
    {"id": 6, "name": "ReflexionAgent", "paper": "Shinn et al., 2023", "capability": "Verbal reinforcement learning", "status": "active"},
    {"id": 7, "name": "ThompsonSamplingAgent", "paper": "Chapelle & Li, NeurIPS 2011", "capability": "Multi-armed bandit rate optimization", "status": "active"},
    {"id": 8, "name": "TelegramAgent", "paper": "Telegram Bot API", "capability": "Telegram command interface", "status": "active"},
    {"id": 9, "name": "BriefingAgent", "paper": "LLM Summarization", "capability": "Daily briefing generation", "status": "active"},
    {"id": 10, "name": "TreeOfThoughtsAgent", "paper": "Yao et al., 2023", "capability": "BFS strategy search", "status": "active"},
    {"id": 11, "name": "SelfDiscoverAgent", "paper": "Zhou et al., 2024", "capability": "Self-composed reasoning structures", "status": "active"},
    {"id": 12, "name": "MixtureOfAgentsAggregator", "paper": "Together AI, 2024", "capability": "Multi-perspective aggregation", "status": "active"},
    {"id": 13, "name": "LLMJudgeAgent", "paper": "Zheng et al., 2023", "capability": "Pairwise evaluation with bias mitigation", "status": "active"},
    {"id": 14, "name": "ProspectTheoryAgent", "paper": "Kahneman & Tversky, 1979 (Nobel)", "capability": "Loss aversion pricing", "status": "active"},
    {"id": 15, "name": "CausalInferenceAgent", "paper": "Pearl, 2000 (Turing Award)", "capability": "Causal reasoning", "status": "active"},
    {"id": 16, "name": "MCTSAgent", "paper": "Silver et al., 2016 (DeepMind)", "capability": "Monte Carlo Tree Search planning", "status": "active"},
    {"id": 17, "name": "ConstitutionalAIAgent", "paper": "Bai et al., 2022 (Anthropic)", "capability": "Self-critique and safety", "status": "active"},
    {"id": 18, "name": "LinUCBAgent", "paper": "Li et al., 2010 (Google)", "capability": "Contextual bandit optimization", "status": "active"},
    {"id": 19, "name": "SurvivalAnalysisAgent", "paper": "Cox, 1972", "capability": "Client churn prediction", "status": "active"},
    {"id": 20, "name": "NashEquilibriumAgent", "paper": "Nash, 1950 (Nobel)", "capability": "Game-theoretic negotiation", "status": "active"},
    {"id": 21, "name": "EpisodicRAGAgent", "paper": "Lewis et al., 2020 (Facebook AI)", "capability": "Retrieval-augmented generation", "status": "active"},
    {"id": 22, "name": "RevenueForecastAgent", "paper": "ARIMA Forecasting", "capability": "Revenue prediction", "status": "active"},
    {"id": 23, "name": "WinCoachAgent", "paper": "Pattern Analysis + Reflexion", "capability": "Proposal coaching", "status": "active"},
    {"id": 24, "name": "ContractGeneratorAgent", "paper": "Legal Document Generation", "capability": "Contract drafting", "status": "active"},
    {"id": 25, "name": "MonthlyBoardAgent", "paper": "CFO-level Reporting", "capability": "Monthly board report", "status": "active"},
    {"id": 26, "name": "AutonomousCollectionAgent", "paper": "Escalation Frameworks", "capability": "Payment collection automation", "status": "active"},
    {"id": 27, "name": "ClientOnboardingAgent", "paper": "Structured Onboarding", "capability": "Client onboarding workflow", "status": "active"},
    {"id": 28, "name": "EODSummaryAgent", "paper": "Business Intelligence", "capability": "End-of-day summary", "status": "active"},
    {"id": 29, "name": "WhatsAppAgent", "paper": "Twilio WhatsApp API", "capability": "WhatsApp command interface", "status": "active"},
    {"id": 30, "name": "AutoJobScoutAgent", "paper": "CoT + Reflexion + EpisodicRAG", "capability": "Autonomous job finding", "status": "active"},
    {"id": 31, "name": "CashFlowRunwayAgent", "paper": "Statistical + Stripe Capital", "capability": "Cash runway prediction", "status": "active"},
    {"id": 32, "name": "SkillEvolutionAgent", "paper": "DSPy + GEPA", "capability": "Playbook evolution from lessons", "status": "active"},
    {"id": 33, "name": "ClientAcquisitionAgent", "paper": "RLHF + AgenticRAG", "capability": "Social lead finding and outreach", "status": "active"},
    {"id": 34, "name": "StripeCapitalAgent", "paper": "Revenue-Based Financing", "capability": "Stripe Capital application drafting", "status": "active"},
    {"id": 35, "name": "SkillDistillAgent", "paper": "Trajectory Distillation", "capability": "SKILL.md export from trajectories", "status": "active"},
    {"id": 36, "name": "MarketSensingAgent", "paper": "OODA Loop + Bayesian", "capability": "Finds urgent buyer pains and budgets", "status": "active"},
    {"id": 37, "name": "OfferLabAgent", "paper": "Value-based Pricing", "capability": "Designs high-margin productized offers", "status": "active"},
    {"id": 38, "name": "ExperimentDesignerAgent", "paper": "Popper + Thompson Sampling", "capability": "Falsifiable 24-72h growth experiments", "status": "active"},
    {"id": 39, "name": "LaunchCommanderAgent", "paper": "Expected Value Decision Theory", "capability": "Ranks offers by EV, builds launch plan", "status": "active"},
    {"id": 40, "name": "RevenueSwarmChief", "paper": "Multi-agent Red Team", "capability": "Orchestrates full revenue swarm loop", "status": "active"},
    {"id": 41, "name": "ClientCloserAgent", "paper": "Reflexion + SkillEvolution", "capability": "Autonomous prospect to proposal to follow-up to win/loss", "status": "active"},
]

MCP_TOOLS = [
    {"name": "create_invoice", "description": "Create invoice + Stripe hosted payment link.", "inputSchema": {"type": "object", "properties": {"client": {"type": "string"}, "amount": {"type": "number"}, "dueDate": {"type": "string"}}, "required": ["client", "amount", "dueDate"]}},
    {"name": "list_invoices", "description": "List invoices.", "inputSchema": {"type": "object", "properties": {"status": {"type": "string"}}}},
    {"name": "get_invoice", "description": "Get single invoice.", "inputSchema": {"type": "object", "properties": {"id": {"type": "string"}}, "required": ["id"]}},
    {"name": "mark_invoice_paid", "description": "Mark invoice as paid.", "inputSchema": {"type": "object", "properties": {"id": {"type": "string"}}, "required": ["id"]}},
    {"name": "send_invoice", "description": "Send invoice via Stripe.", "inputSchema": {"type": "object", "properties": {"id": {"type": "string"}}, "required": ["id"]}},
    {"name": "send_invoice_reminder", "description": "Send invoice reminder.", "inputSchema": {"type": "object", "properties": {"id": {"type": "string"}}, "required": ["id"]}},
    {"name": "delete_invoice", "description": "Delete invoice.", "inputSchema": {"type": "object", "properties": {"id": {"type": "string"}}, "required": ["id"]}},
    {"name": "list_clients", "description": "List all clients.", "inputSchema": {"type": "object", "properties": {}}},
    {"name": "add_client", "description": "Add a new client.", "inputSchema": {"type": "object", "properties": {"name": {"type": "string"}, "company": {"type": "string"}, "email": {"type": "string"}}, "required": ["name"]}},
    {"name": "create_proposal", "description": "Create a proposal.", "inputSchema": {"type": "object", "properties": {"title": {"type": "string"}, "client": {"type": "string"}}, "required": ["title", "client"]}},
    {"name": "record_proposal_outcome", "description": "Record proposal win/loss with Reflexion.", "inputSchema": {"type": "object", "properties": {"proposalId": {"type": "string"}, "outcome": {"type": "string"}}, "required": ["proposalId", "outcome"]}},
    {"name": "get_win_intelligence", "description": "Get win rate intelligence.", "inputSchema": {"type": "object", "properties": {}}},
    {"name": "get_kpis", "description": "Live KPIs dashboard data.", "inputSchema": {"type": "object", "properties": {}}},
    {"name": "get_live_dashboard", "description": "Full live dashboard.", "inputSchema": {"type": "object", "properties": {}}},
    {"name": "debate_proposal", "description": "CAMEL multi-agent debate.", "inputSchema": {"type": "object", "properties": {"task": {"type": "string"}}, "required": ["task"]}},
    {"name": "react_agent", "description": "ReAct reason-act-observe loop.", "inputSchema": {"type": "object", "properties": {"task": {"type": "string"}}, "required": ["task"]}},
    {"name": "score_proposal_cot", "description": "Chain-of-Thought proposal scoring.", "inputSchema": {"type": "object", "properties": {"proposal": {"type": "string"}}, "required": ["proposal"]}},
    {"name": "anomaly_scan", "description": "Anomaly detection.", "inputSchema": {"type": "object", "properties": {}}},
    {"name": "tree_of_thoughts", "description": "Tree of Thoughts BFS search.", "inputSchema": {"type": "object", "properties": {"task": {"type": "string"}}, "required": ["task"]}},
    {"name": "self_discover", "description": "Self-Discover reasoning.", "inputSchema": {"type": "object", "properties": {"task": {"type": "string"}}, "required": ["task"]}},
    {"name": "mixture_of_agents", "description": "Mixture of Agents aggregation.", "inputSchema": {"type": "object", "properties": {"task": {"type": "string"}}, "required": ["task"]}},
    {"name": "llm_judge", "description": "LLM-as-Judge pairwise evaluation.", "inputSchema": {"type": "object", "properties": {"a": {"type": "string"}, "b": {"type": "string"}}, "required": ["a", "b"]}},
    {"name": "reflexion_review", "description": "Reflexion verbal reinforcement.", "inputSchema": {"type": "object", "properties": {"outcome": {"type": "string"}}, "required": ["outcome"]}},
    {"name": "thompson_sampling_rate", "description": "Thompson Sampling rate optimization.", "inputSchema": {"type": "object", "properties": {}}},
    {"name": "episodic_rag", "description": "EpisodicRAG retrieval-augmented generation.", "inputSchema": {"type": "object", "properties": {"query": {"type": "string"}}, "required": ["query"]}},
    {"name": "prospect_theory_price", "description": "Prospect Theory loss-aversion pricing.", "inputSchema": {"type": "object", "properties": {"basePrice": {"type": "number"}}, "required": ["basePrice"]}},
    {"name": "causal_inference", "description": "Causal inference reasoning.", "inputSchema": {"type": "object", "properties": {"question": {"type": "string"}}, "required": ["question"]}},
    {"name": "mcts_plan", "description": "Monte Carlo Tree Search planning.", "inputSchema": {"type": "object", "properties": {"goal": {"type": "string"}}, "required": ["goal"]}},
    {"name": "constitutional_ai_check", "description": "Constitutional AI safety check.", "inputSchema": {"type": "object", "properties": {"content": {"type": "string"}}, "required": ["content"]}},
    {"name": "linucb_optimize", "description": "LinUCB contextual bandit optimization.", "inputSchema": {"type": "object", "properties": {}}},
    {"name": "survival_analysis", "description": "Cox survival analysis for client churn.", "inputSchema": {"type": "object", "properties": {}}},
    {"name": "nash_negotiate", "description": "Nash Equilibrium negotiation.", "inputSchema": {"type": "object", "properties": {"scenario": {"type": "string"}}, "required": ["scenario"]}},
    {"name": "revenue_forecast", "description": "ARIMA revenue forecasting.", "inputSchema": {"type": "object", "properties": {}}},
    {"name": "win_coach", "description": "Win rate coach with Reflexion.", "inputSchema": {"type": "object", "properties": {"proposal": {"type": "string"}}, "required": ["proposal"]}},
    {"name": "generate_contract", "description": "Legal contract generation.", "inputSchema": {"type": "object", "properties": {"client": {"type": "string"}, "scope": {"type": "string"}}, "required": ["client", "scope"]}},
    {"name": "monthly_board_report", "description": "CFO-level monthly board report.", "inputSchema": {"type": "object", "properties": {}}},
    {"name": "autonomous_collection", "description": "Autonomous payment collection.", "inputSchema": {"type": "object", "properties": {}}},
    {"name": "client_onboarding", "description": "Structured client onboarding.", "inputSchema": {"type": "object", "properties": {"client": {"type": "string"}}, "required": ["client"]}},
    {"name": "eod_summary", "description": "End-of-day business summary.", "inputSchema": {"type": "object", "properties": {}}},
    {"name": "auto_job_scout", "description": "AutoJobScout: finds jobs, scores, drafts proposals.", "inputSchema": {"type": "object", "properties": {"skills": {"type": "string"}, "count": {"type": "number"}}}},
    {"name": "cash_flow_runway", "description": "CashFlowRunway: predicts days of cash left.", "inputSchema": {"type": "object", "properties": {}}},
    {"name": "skill_evolution", "description": "SkillEvolution: rewrites playbook. DSPy+GEPA.", "inputSchema": {"type": "object", "properties": {}}},
    {"name": "client_acquisition", "description": "ClientAcquisition: finds social leads.", "inputSchema": {"type": "object", "properties": {"skills": {"type": "string"}, "maxLeads": {"type": "number"}}}},
    {"name": "stripe_capital", "description": "StripeCapital: drafts financing application.", "inputSchema": {"type": "object", "properties": {"runwayDays": {"type": "number"}}}},
    {"name": "skill_distill_export", "description": "SkillDistill: exports live SKILL.md.", "inputSchema": {"type": "object", "properties": {}}},
    {"name": "get_skill_history", "description": "Full versioned history of evolved playbooks.", "inputSchema": {"type": "object", "properties": {}}},
    {"name": "market_sensing", "description": "v11 MarketSensing: finds urgent buyer pains.", "inputSchema": {"type": "object", "properties": {}}},
    {"name": "offer_lab", "description": "v11 OfferLab: designs high-margin offers.", "inputSchema": {"type": "object", "properties": {}}},
    {"name": "experiment_designer", "description": "v11 ExperimentDesigner: falsifiable experiments.", "inputSchema": {"type": "object", "properties": {}}},
    {"name": "launch_commander", "description": "v11 LaunchCommander: ranks offers by EV.", "inputSchema": {"type": "object", "properties": {}}},
    {"name": "revenue_swarm", "description": "v11 RevenueSwarm: full autonomous scientist loop.", "inputSchema": {"type": "object", "properties": {}}},
    {"name": "revenue_swarm_status", "description": "v11 Revenue Swarm status.", "inputSchema": {"type": "object", "properties": {}}},
    {"name": "close_client_loop", "description": "v12 AutonomousCloserLoop.", "inputSchema": {"type": "object", "properties": {"skills": {"type": "string"}, "count": {"type": "number"}}}},
    {"name": "client_prospect", "description": "v12 ClientProspector: fresh leads.", "inputSchema": {"type": "object", "properties": {"skills": {"type": "string"}, "count": {"type": "number"}}}},
    {"name": "draft_proposal_ai", "description": "v12 ProposalDraft: Hermes 3 + Reflexion.", "inputSchema": {"type": "object", "properties": {"prospect": {"type": "object"}}, "required": ["prospect"]}},
    {"name": "send_proposal", "description": "v12 ProposalSender: sends proposal via Telegram.", "inputSchema": {"type": "object", "properties": {"proposal": {"type": "object"}}, "required": ["proposal"]}},
    {"name": "check_followups", "description": "v12 FollowUpTimer: auto-sends 24h follow-ups.", "inputSchema": {"type": "object", "properties": {}}},
    {"name": "closer_outcome", "description": "v12 OutcomeTracker: records win/loss.", "inputSchema": {"type": "object", "properties": {"closerId": {"type": "string"}, "outcome": {"type": "string"}}, "required": ["closerId", "outcome"]}},
    {"name": "closer_status", "description": "v12 ClientCloser queue status.", "inputSchema": {"type": "object", "properties": {}}},
    {"name": "get_agent_card", "description": "A2A Agent Card.", "inputSchema": {"type": "object", "properties": {}}},
    {"name": "get_mpp_config", "description": "Machine Payments Protocol config.", "inputSchema": {"type": "object", "properties": {}}},
    {"name": "get_reputation_vc", "description": "W3C Verifiable Credential v2.1.", "inputSchema": {"type": "object", "properties": {}}},
    {"name": "get_profile", "description": "Public freelancer profile.", "inputSchema": {"type": "object", "properties": {"handle": {"type": "string"}}}},
    {"name": "daily_ops_plan", "description": "Autonomous daily operations plan.", "inputSchema": {"type": "object", "properties": {}}},
    {"name": "x402_payment_proof", "description": "Verify x402 on-chain payment proof.", "inputSchema": {"type": "object", "properties": {"invoiceId": {"type": "string"}, "txHash": {"type": "string"}}, "required": ["invoiceId", "txHash"]}},
    {"name": "get_activities", "description": "Activity feed.", "inputSchema": {"type": "object", "properties": {}}},
    {"name": "get_analytics", "description": "Analytics data.", "inputSchema": {"type": "object", "properties": {}}},
    {"name": "get_benchmark", "description": "Benchmark scores 10.0/10.0.", "inputSchema": {"type": "object", "properties": {}}},
    {"name": "get_demo", "description": "Live showcase of all 14 key features for judges.", "inputSchema": {"type": "object", "properties": {}}},
    {"name": "get_metrics", "description": "Uptime, security, protocols, integrations metrics.", "inputSchema": {"type": "object", "properties": {}}},
]
